# Generated by Django 4.1.1 on 2022-09-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Profile", "0003_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
