# Generated by Django 4.0.6 on 2022-09-05 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('cover_picture', models.URLField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=312)),
                ('online', models.BooleanField(default=False)),
                ('last_online', models.DateTimeField(auto_now=True)),
                ('is_on_boarding_complete', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='profile Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
