# Generated by Django 4.1.4 on 2023-01-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, max_length=512, null=True, upload_to=""
            ),
        ),
    ]
