# Generated by Django 4.1.4 on 2023-01-02 17:44

import apps.core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cover_picture",
            field=apps.core.models.ImageField(
                blank=True, max_length=1000, null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=apps.core.models.ImageField(
                blank=True, max_length=1000, null=True, upload_to=""
            ),
        ),
    ]
